version: "3.9"

networks:
  karim-network:
    driver: bridge

volumes:
  mysql-data:

services:
  ### PHP / Symfony ###
  php:
    build:
      context: ./backend/php
      dockerfile: Dockerfile
    image: php:8.3-fpm
    container_name: php83
    volumes:
      - ./backend:/var/www/backend
    networks:
      - karim-network

  ### NGINX ###
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./backend:/var/www/backend
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - karim-network

  ### MYSQL ###
  mysql:
    image: mysql:8.0
    container_name: mysql84
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - karim-network

  ### PHPMYADMIN ###
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8087:80"
    depends_on:
      - mysql
    networks:
      - karim-network

  ### ANGULAR ###
  angular:
    image: node:20
    container_name: angular
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "4200:4200"
    networks:
      - karim-network
